version: '2.3'

services:
  main-service:
    build: ./main-service
    container_name: main-service
    environment:
      - 'spring.datasource.url=jdbc:postgresql://postgres_test_db:5432/postgres'
      - 'spring.datasource.hikari.schema=test_schema'
    ports:
      - "9090:9090"
    depends_on:
      - postgres_test_db
  postgres_test_db:
    image: postgres:13.3
    container_name: postgres_test_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./docker-init/docker-init.sql:/docker-entrypoint-initdb.d/docker-init.sql

